SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION addnums(N1 IN NUMBER, N2 IN NUMBER)
RETURN NUMBER IS
    RESULT NUMBER;
BEGIN
    RESULT := N1 + N2;
    RETURN RESULT;
END addnums;
/

DECLARE
    ANS NUMBER;
BEGIN
    ANS := addnums(&a, &b);
    DBMS_OUTPUT.PUT_LINE('SUM = ' || ANS);
END;
/
